#!/bin/bash

THIS_DIR=`pwd`

VIM_REPOS=(
    "https://github.com/mileszs/ack.vim"
    "https://github.com/ctrlpvim/ctrlp.vim"
    "https://github.com/w0rp/ale"
    "https://github.com/mkitt/tabline.vim"
    "https://github.com/bling/vim-airline"
    "https://github.com/Chiel92/vim-autoformat"
    "https://github.com/tpope/vim-fugitive"
    "https://github.com/tpope/vim-rhubarb"
    "https://github.com/airblade/vim-gitgutter"
    "https://github.com/pangloss/vim-javascript"
    "https://github.com/mxw/vim-jsx"
    "https://github.com/mrkschan/vim-node-jslint"
    "https://github.com/maksimr/vim-jsbeautify"
    "https://github.com/einars/js-beautify"
    "https://github.com/christoomey/vim-tmux-navigator"
    "https://github.com/jmcantrell/vim-virtualenv"
    "https://github.com/FelikZ/ctrlp-py-matcher"
    "https://github.com/chase/vim-ansible-yaml"
    "https://github.com/davidhalter/jedi-vim"
    "https://github.com/ervandew/supertab"
)

echo $VIM_REPOS

# basic configs
ln -sf $THIS_DIR/vimrc ~/.vimrc
ln -sf $THIS_DIR/tmux.conf ~/.tmux.conf
ln -sf $THIS_DIR/bash_profile ~/.bash_profile
ln -sf $THIS_DIR/hgignore ~/.hgignore
ln -sf $THIS_DIR/set_ps1 ~/.set_ps1
ln -sf $THIS_DIR/git-prompt.sh ~/.git-prompt.sh

# reusable scripts
if [ ! -d ~/scripts ]; then mkdir ~/scripts ; fi
cp -rp $THIS_DIR/scripts/* ~/scripts

chmod u+x $THIS_DIR/scripts/*

for vr in ${VIM_REPOS[@]} ;
do
    vr_name=`echo $vr | sed -E 's/.*\/([^\/]+)$/\1/'`
    cd ~/.vim/bundle/
    if [ ! -d $vr_name ]
    then
        echo "Cloning $vr into $vr_name"
        git clone --recursive $vr
    else
        echo "Updating $vr_name"
        cd $vr_name ; git pull
    fi
done ;

# tmux plugins
if [ ! -d ~/.tmux ]; then mkdir ~/.tmux && mkdir ~/.tmux/plugins ; fi

if [ ! -d ~/.tmux/plugins/tpm ]
then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
else
    cd ~/.tmux/plugins/tpm ; git pull
fi

source $THIS_DIR/git.config
source ~/.bash_profile
