#!/bin/bash

THIS_DIR=`pwd`

VIM_REPOS=(
    "https://github.com/mileszs/ack.vim"
    "https://github.com/ctrlpvim/ctrlp.vim"
    "https://github.com/w0rp/ale"
    "https://github.com/mxw/vim-jsx"
    "https://github.com/bling/vim-airline"
    "https://github.com/tpope/vim-fugitive"
    "https://github.com/airblade/vim-gitgutter"
    "https://github.com/christoomey/vim-tmux-navigator"
    "https://github.com/davidhalter/jedi-vim"
)

curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.git-prompt.sh

# basic configs
ln -sf $THIS_DIR/vimrc ~/.vimrc
ln -sf $THIS_DIR/tmux.conf ~/.tmux.conf
ln -sf $THIS_DIR/bash_profile ~/.bash_profile
ln -sf $THIS_DIR/bash_local ~/.bash_local
ln -sf $THIS_DIR/hgignore ~/.hgignore
ln -sf $THIS_DIR/set_ps1 ~/.set_ps1
ln -sf $THIS_DIR/git-prompt.sh ~/.git-prompt.sh

# reusable scripts
if [ ! -d ~/scripts ]; then mkdir ~/scripts ; fi
cp -rp $THIS_DIR/scripts/* ~/scripts

chmod u+x $THIS_DIR/scripts/*

for vr in ${VIM_REPOS[@]} ;
do
    vr_name=`echo $vr | sed -E 's/.*\/([^\/]+)$/\1/'`
    VIM_PATH=~/.vim/bundle
    echo "Cloning into $vr_name"
    if [ ! -d "$VIM_PATH/$vr_name" ]
    then
        echo "Cloning $vr into $vr_name"
        git clone --recursive $vr $VIM_PATH/$vr_name
    else
        echo "Updating $vr_name"
        cd $VIM_PATH/$vr_name ; git pull
    fi
done ;

# tmux plugins
if [ ! -d ~/.tmux ]; then mkdir ~/.tmux && mkdir ~/.tmux/plugins ; fi

if [ ! -d ~/.tmux/plugins/tpm ]
then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
else
    cd ~/.tmux/plugins/tpm ; git pull
fi

source $THIS_DIR/git.config
source ~/.bash_profile
