#!/bin/bash

# Don't forget to activate this in .bashrc or .bash_profile (source ~/.set_ps1.sh)

# curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.git-prompt.sh

source ~/.git-prompt.sh

PS1=$'\[\e[0;36m\][\u] \[\e[1;33m\]\w \[\e[0;32m\]$(__git_ps1 " (%s)") \[\e[0m\]\n \xe2\x86\xaa '
export PS1
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
