#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: img_sync <folder_name>"
    exit 0
fi

CURR_DIR=${PWD##*/}

if [ "$CURR_DIR" !=  "gapadventures" ]; then
    echo "You should be inside the repo at /path/to/gadventures.com/gapadventures"
    exit 0
fi

FOLDER=$1

python manage.py sync_from_media_server --confirm\
    production media-server/$FOLDER media-server/$FOLDER \
    --exclude 'admin/offline-maps*' \
    --exclude 'admin/brochures*' \
    --exclude 'wateringhole*' \
    --exclude 'sherpa*' \
    --exclude 'looptail*' \
    --exclude 'admin/itinerary-pdfs*' \
    --exclude 'admin/pagespeed*' \
    --exclude 'admin/triplog_files*' \
    --exclude 'admin/reports*' \
    --exclude 'admin/trip-editor/reports*'\
    --delete
